### ISSUE TITLE
Can't start project

### ISSUE THREAD

**Issue by snguyen23** [manekinekko/angular-web-bluetooth#62]
I'm trying to start the project, but I've gotten several errors. After running `npm install`, got the following:

```
Time Elapsed 00:00:34.88
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Projects\angular-web-bluetooth\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Projects\\angular-web-bluetooth\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Projects\angular-web-bluetooth\node_modules\node-sass
gyp ERR! node -v v12.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\snguyen\AppData\Roaming\npm-cache\_logs\2020-02-28T17_33_54_255Z-debug.log

```

After running `npm run build`:

```
Cannot find module 'ng-packagr'
Require stack:
- C:\Projects\angular-web-bluetooth\node_modules\@angular-devkit\build-ng-packagr\src\build\index.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\index.js    
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\models\architect-command.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\commands\build-impl.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\utilities\json-schema.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\models\command-runner.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\lib\cli\index.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\lib\init.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\bin\ng
Error: Cannot find module 'ng-packagr'
Require stack:
- C:\Projects\angular-web-bluetooth\node_modules\@angular-devkit\build-ng-packagr\src\build\index.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\architect.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\node_modules\@angular-devkit\architect\src\index.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\models\architect-command.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\commands\build-impl.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\utilities\json-schema.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\models\command-runner.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\lib\cli\index.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\lib\init.js
- C:\Projects\angular-web-bluetooth\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
    at requireProjectModule (C:\Projects\angular-web-bluetooth\node_modules\@angular-devkit\build-ng-packagr\src\build\index.js:19:28)
    at Observable._subscribe (C:\Projects\angular-web-bluetooth\node_modules\@angular-devkit\build-ng-packagr\src\build\index.js:57:38)
    at Observable._trySubscribe (C:\Projects\angular-web-bluetooth\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\Projects\angular-web-bluetooth\node_modules\rxjs\internal\Observable.js:30:22)
    at C:\Projects\angular-web-bluetooth\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\Projects\angular-web-bluetooth\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (C:\Projects\angular-web-bluetooth\node_modules\rxjs\internal\operators\mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (C:\Projects\angular-web-bluetooth\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-web-bluetooth-starter@3.0.0 prebuild: `ng build @manekinekko/angular-web-bluetooth`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-web-bluetooth-starter@3.0.0 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\snguyen\AppData\Roaming\npm-cache\_logs\2020-02-28T17_35_39_492Z-debug.log
```

**Comment by manekinekko** [comment]
could you try with the latest release?

**Comment by manekinekko** [comment]
Please reopen the issue if you're still have a problem with the latest release.
